### ISSUE TITLE
Values in joint_limits.yaml for MoveIT

### ISSUE THREAD

**Issue by matthias-mayr** [IFL-CAMP/iiwa_stack#248]
The file [joint_limits.yaml](https://github.com/IFL-CAMP/iiwa_stack/blob/master/iiwa_moveit/config/joint_limits.yaml) defines velocity limits for MoveIT:

```
joint_limits:
  iiwa_joint_1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
```
Shouldn't those limits be the same ones that are imposed by the real robot? So for example a `max_velocity` of 1.7104 for the first joint for an `iiwa7`?
